#!/bin/sh
#
# hsm-agent  HSM Storage Agent Service
#
# chkconfig:   - 98 02
# description: HSM Storage Agent Service works on Ceph Storage System.
### END INIT INFO

. /etc/rc.d/init.d/functions

prog=hsm-agent
exec="/usr/bin/$prog"
config="/etc/hsm/hsm.conf"
pidfile="/var/run/hsm/$prog.pid"
logfile=/var/log/hsm/hsm-agent.log

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog
if [ ! -d /var/run/hsm ]; then
    mkdir -p /var/run/hsm
    chown -R hsm /var/run/hsm
fi

lockfile=/var/lock/subsys/$prog


start() {
    [ -x $exec ] || exit 5
    [ -f $config ] || exit 6
    echo -n $"Starting $prog: "
    daemon --user hsm --pidfile $pidfile "$exec --config-file $config --log-file $logfile &>/dev/null & echo \$! > $pidfile"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

clean() {
    rm -rf $pidfile
    rm -rf $lockfile
}
restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status -p $pidfile $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    clean)
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
