all:
	g++ server1.cpp io_pool.cpp -std=c++14 -lboost_thread -lboost_system -pthread -o server
#	g++ client1.cpp  -std=c++11 -lboost_thread -lboost_system -pthread -o client
clean:
	rm client server -f
